var albumTracksResponse = {
  "href": "https://api.spotify.com/v1/albums/2kZonOzsrnp9H9gMxUUfqr/tracks?offset=0&limit=10",
  "items": [
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 149091,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/0HQL20mk9GCvzqLjqU7n80"
      },
      "href": "https://api.spotify.com/v1/tracks/0HQL20mk9GCvzqLjqU7n80",
      "id": "0HQL20mk9GCvzqLjqU7n80",
      "is_local": false,
      "name": "Kapitel 1 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/564df89fb18617f090a40a12b49acd7a6ee5c132?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:0HQL20mk9GCvzqLjqU7n80"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 175061,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/6BbRpYeDnIPD2k5IYGlZC8"
      },
      "href": "https://api.spotify.com/v1/tracks/6BbRpYeDnIPD2k5IYGlZC8",
      "id": "6BbRpYeDnIPD2k5IYGlZC8",
      "is_local": false,
      "name": "Kapitel 2 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/6e37d607ce24d88bae4ed3f4c558dfde699d4967?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 2,
      "type": "track",
      "uri": "spotify:track:6BbRpYeDnIPD2k5IYGlZC8"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 102037,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/4YcxeD2VUpF0PBIhlzwZof"
      },
      "href": "https://api.spotify.com/v1/tracks/4YcxeD2VUpF0PBIhlzwZof",
      "id": "4YcxeD2VUpF0PBIhlzwZof",
      "is_local": false,
      "name": "Kapitel 3 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/c989affd31f3375b53104c8a8d038f34952082f7?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 3,
      "type": "track",
      "uri": "spotify:track:4YcxeD2VUpF0PBIhlzwZof"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 129691,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/4VaH9lYLiacK72gdZHVCtr"
      },
      "href": "https://api.spotify.com/v1/tracks/4VaH9lYLiacK72gdZHVCtr",
      "id": "4VaH9lYLiacK72gdZHVCtr",
      "is_local": false,
      "name": "Kapitel 4 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/c1e79c3ed63c008a6f9edc718d863e2d62cbd7c6?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 4,
      "type": "track",
      "uri": "spotify:track:4VaH9lYLiacK72gdZHVCtr"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 106645,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/0TTG3mqvmEgdZjdXDUy53i"
      },
      "href": "https://api.spotify.com/v1/tracks/0TTG3mqvmEgdZjdXDUy53i",
      "id": "0TTG3mqvmEgdZjdXDUy53i",
      "is_local": false,
      "name": "Kapitel 5 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/82c860a62f51179599fd18d01eb16e9c2591c171?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 5,
      "type": "track",
      "uri": "spotify:track:0TTG3mqvmEgdZjdXDUy53i"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 143626,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/2BTYtGpQEwvEvTMzPVK26W"
      },
      "href": "https://api.spotify.com/v1/tracks/2BTYtGpQEwvEvTMzPVK26W",
      "id": "2BTYtGpQEwvEvTMzPVK26W",
      "is_local": false,
      "name": "Kapitel 6 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/7e3a2d1cf3a995d0e932a5aec9df2ee0d54f52cf?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 6,
      "type": "track",
      "uri": "spotify:track:2BTYtGpQEwvEvTMzPVK26W"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 117540,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/2UQ62PnsDD0xGaJEI7gXh4"
      },
      "href": "https://api.spotify.com/v1/tracks/2UQ62PnsDD0xGaJEI7gXh4",
      "id": "2UQ62PnsDD0xGaJEI7gXh4",
      "is_local": false,
      "name": "Kapitel 7 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/b193d9280832296cff309e7c60bc04b96bd2029f?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 7,
      "type": "track",
      "uri": "spotify:track:2UQ62PnsDD0xGaJEI7gXh4"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 230151,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/0LBTTdNvmq2j6TxagJbUko"
      },
      "href": "https://api.spotify.com/v1/tracks/0LBTTdNvmq2j6TxagJbUko",
      "id": "0LBTTdNvmq2j6TxagJbUko",
      "is_local": false,
      "name": "Kapitel 8 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/5d24346b5b5e015e569b7ddb458218370285a114?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 8,
      "type": "track",
      "uri": "spotify:track:0LBTTdNvmq2j6TxagJbUko"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 114969,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/33G97jyVTPSN59re0YJN6d"
      },
      "href": "https://api.spotify.com/v1/tracks/33G97jyVTPSN59re0YJN6d",
      "id": "33G97jyVTPSN59re0YJN6d",
      "is_local": false,
      "name": "Kapitel 9 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/67898ea2ce9d0880b0171d0a8f3e4c3e75dd510b?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 9,
      "type": "track",
      "uri": "spotify:track:33G97jyVTPSN59re0YJN6d"
    },
    {
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
          },
          "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
          "id": "5Qay5yizWXqdijRvNd5KX2",
          "name": "Edward Snowden",
          "type": "artist",
          "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/73PFvL0Hca4IzWsHKSakc1"
          },
          "href": "https://api.spotify.com/v1/artists/73PFvL0Hca4IzWsHKSakc1",
          "id": "73PFvL0Hca4IzWsHKSakc1",
          "name": "N.N.",
          "type": "artist",
          "uri": "spotify:artist:73PFvL0Hca4IzWsHKSakc1"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MV",
        "MW",
        "MX",
        "MY",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 160150,
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/track/6kbM7QF7tucs69xCokOOrl"
      },
      "href": "https://api.spotify.com/v1/tracks/6kbM7QF7tucs69xCokOOrl",
      "id": "6kbM7QF7tucs69xCokOOrl",
      "is_local": false,
      "name": "Kapitel 10 - Permanent Record - Meine Geschichte",
      "preview_url": "https://p.scdn.co/mp3-preview/c217bbf422bf272efa3010a62bfb76bce7c1380d?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 10,
      "type": "track",
      "uri": "spotify:track:6kbM7QF7tucs69xCokOOrl"
    }
  ],
  "limit": 10,
  // "next": "https://api.spotify.com/v1/albums/2kZonOzsrnp9H9gMxUUfqr/tracks?offset=10&limit=10",
  "offset": 0,
  "previous": null,
  "total": 260
}

var albumSearchResponse = {
  "albums": {
    "href": "https://api.spotify.com/v1/search?query=Edward+Snowden&type=album&offset=0&limit=20",
    "items": [
      {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5Qay5yizWXqdijRvNd5KX2"
            },
            "href": "https://api.spotify.com/v1/artists/5Qay5yizWXqdijRvNd5KX2",
            "id": "5Qay5yizWXqdijRvNd5KX2",
            "name": "Edward Snowden",
            "type": "artist",
            "uri": "spotify:artist:5Qay5yizWXqdijRvNd5KX2"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MV",
          "MW",
          "MX",
          "MY",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZW"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/2kZonOzsrnp9H9gMxUUfqr"
        },
        "href": "https://api.spotify.com/v1/albums/2kZonOzsrnp9H9gMxUUfqr",
        "id": "2kZonOzsrnp9H9gMxUUfqr",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b2730a7a345e406383361f7e61b4",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e020a7a345e406383361f7e61b4",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d000048510a7a345e406383361f7e61b4",
            "width": 64
          }
        ],
        "name": "Permanent Record - Meine Geschichte (Ungekürzte Lesung)",
        "release_date": "2020-02-01",
        "release_date_precision": "day",
        "total_tracks": 260,
        "type": "album",
        "uri": "spotify:album:2kZonOzsrnp9H9gMxUUfqr"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2082IQzWLNrxo4YQPHqOmi"
            },
            "href": "https://api.spotify.com/v1/artists/2082IQzWLNrxo4YQPHqOmi",
            "id": "2082IQzWLNrxo4YQPHqOmi",
            "name": "Sebastian Lee",
            "type": "artist",
            "uri": "spotify:artist:2082IQzWLNrxo4YQPHqOmi"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MV",
          "MW",
          "MX",
          "MY",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZW"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/0lkEYNJERu8LLe2pGTOzVQ"
        },
        "href": "https://api.spotify.com/v1/albums/0lkEYNJERu8LLe2pGTOzVQ",
        "id": "0lkEYNJERu8LLe2pGTOzVQ",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b273eb1c86a14d046c2db9738d6f",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e02eb1c86a14d046c2db9738d6f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d00004851eb1c86a14d046c2db9738d6f",
            "width": 64
          }
        ],
        "name": "Edward Snowden",
        "release_date": "2020-09-30",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:0lkEYNJERu8LLe2pGTOzVQ"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5PowvAt9c7v3xqfryBLMI7"
            },
            "href": "https://api.spotify.com/v1/artists/5PowvAt9c7v3xqfryBLMI7",
            "id": "5PowvAt9c7v3xqfryBLMI7",
            "name": "Chronik KID",
            "type": "artist",
            "uri": "spotify:artist:5PowvAt9c7v3xqfryBLMI7"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MV",
          "MW",
          "MX",
          "MY",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZW"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/1dQBQL4ec3DxOkY8JJ2QCa"
        },
        "href": "https://api.spotify.com/v1/albums/1dQBQL4ec3DxOkY8JJ2QCa",
        "id": "1dQBQL4ec3DxOkY8JJ2QCa",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b2732ccaad11b087243a22ed8772",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e022ccaad11b087243a22ed8772",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d000048512ccaad11b087243a22ed8772",
            "width": 64
          }
        ],
        "name": "Edward Snowden",
        "release_date": "2020-12-25",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:1dQBQL4ec3DxOkY8JJ2QCa"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1xvsA9I2XQJXcQEYDpIrU9"
            },
            "href": "https://api.spotify.com/v1/artists/1xvsA9I2XQJXcQEYDpIrU9",
            "id": "1xvsA9I2XQJXcQEYDpIrU9",
            "name": "Albert Fichter",
            "type": "artist",
            "uri": "spotify:artist:1xvsA9I2XQJXcQEYDpIrU9"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MV",
          "MW",
          "MX",
          "MY",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZW"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/5LaMPB3qpBLKDJstelGPTK"
        },
        "href": "https://api.spotify.com/v1/albums/5LaMPB3qpBLKDJstelGPTK",
        "id": "5LaMPB3qpBLKDJstelGPTK",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b27321cf0fcf8c64498b23bbd777",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e0221cf0fcf8c64498b23bbd777",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d0000485121cf0fcf8c64498b23bbd777",
            "width": 64
          }
        ],
        "name": "Another Chance for Edward Snowden",
        "release_date": "2019-06-25",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:5LaMPB3qpBLKDJstelGPTK"
      },
      {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4xPxOC7r1FDBvjSjmnaRLp"
            },
            "href": "https://api.spotify.com/v1/artists/4xPxOC7r1FDBvjSjmnaRLp",
            "id": "4xPxOC7r1FDBvjSjmnaRLp",
            "name": "Matthew Collings",
            "type": "artist",
            "uri": "spotify:artist:4xPxOC7r1FDBvjSjmnaRLp"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MV",
          "MW",
          "MX",
          "MY",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZW"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/5c8SPwF4Mi8VRgNIVTYiW3"
        },
        "href": "https://api.spotify.com/v1/albums/5c8SPwF4Mi8VRgNIVTYiW3",
        "id": "5c8SPwF4Mi8VRgNIVTYiW3",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b273159946024338dca180ec4a26",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e02159946024338dca180ec4a26",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d00004851159946024338dca180ec4a26",
            "width": 64
          }
        ],
        "name": "A Requiem for Edward Snowden",
        "release_date": "2016-03-24",
        "release_date_precision": "day",
        "total_tracks": 8,
        "type": "album",
        "uri": "spotify:album:5c8SPwF4Mi8VRgNIVTYiW3"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/55bvcxAB4zkEuzG2PR1cv9"
            },
            "href": "https://api.spotify.com/v1/artists/55bvcxAB4zkEuzG2PR1cv9",
            "id": "55bvcxAB4zkEuzG2PR1cv9",
            "name": "ShaMANoiD",
            "type": "artist",
            "uri": "spotify:artist:55bvcxAB4zkEuzG2PR1cv9"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MV",
          "MW",
          "MX",
          "MY",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZW"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/3ZmpAuVZW9qy2YwVE8uGsT"
        },
        "href": "https://api.spotify.com/v1/albums/3ZmpAuVZW9qy2YwVE8uGsT",
        "id": "3ZmpAuVZW9qy2YwVE8uGsT",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b273750a52a0b81bdf6b8ba6d0ed",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e02750a52a0b81bdf6b8ba6d0ed",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d00004851750a52a0b81bdf6b8ba6d0ed",
            "width": 64
          }
        ],
        "name": "Cant be Free Feat Edward Snowden",
        "release_date": "2017-11-01",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:3ZmpAuVZW9qy2YwVE8uGsT"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1FbezMRfI2kRrO4OKs40jl"
            },
            "href": "https://api.spotify.com/v1/artists/1FbezMRfI2kRrO4OKs40jl",
            "id": "1FbezMRfI2kRrO4OKs40jl",
            "name": "Ganfunkel",
            "type": "artist",
            "uri": "spotify:artist:1FbezMRfI2kRrO4OKs40jl"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MV",
          "MW",
          "MX",
          "MY",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZW"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/3s7tO6MEsHSba5bAPfYHrG"
        },
        "href": "https://api.spotify.com/v1/albums/3s7tO6MEsHSba5bAPfYHrG",
        "id": "3s7tO6MEsHSba5bAPfYHrG",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b27358b1bd6f0a2cac473fd38cca",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e0258b1bd6f0a2cac473fd38cca",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d0000485158b1bd6f0a2cac473fd38cca",
            "width": 64
          }
        ],
        "name": "The Outlaw Edward Snowden, Vol. 1",
        "release_date": "2016-05-20",
        "release_date_precision": "day",
        "total_tracks": 3,
        "type": "album",
        "uri": "spotify:album:3s7tO6MEsHSba5bAPfYHrG"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/55bvcxAB4zkEuzG2PR1cv9"
            },
            "href": "https://api.spotify.com/v1/artists/55bvcxAB4zkEuzG2PR1cv9",
            "id": "55bvcxAB4zkEuzG2PR1cv9",
            "name": "ShaMANoiD",
            "type": "artist",
            "uri": "spotify:artist:55bvcxAB4zkEuzG2PR1cv9"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MV",
          "MW",
          "MX",
          "MY",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZW"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/6QbguyB3URNar9izLJgi3O"
        },
        "href": "https://api.spotify.com/v1/albums/6QbguyB3URNar9izLJgi3O",
        "id": "6QbguyB3URNar9izLJgi3O",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b273511bc64f02c3e940ead38a17",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e02511bc64f02c3e940ead38a17",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d00004851511bc64f02c3e940ead38a17",
            "width": 64
          }
        ],
        "name": "Cant be Free Feat Edward Snowden",
        "release_date": "2017-11-01",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:6QbguyB3URNar9izLJgi3O"
      }
    ],
    "limit": 20,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 8
  }
}

module.exports = {
  albumSearchResponse,
  albumTracksResponse,
}
